# Generated by Django 5.2.4 on 2025-07-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('priority', models.IntegerField(default=1, help_text='1=Low, 2=Medium, 3=High')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief description of the additional activity', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what was done')),
                ('category', models.CharField(choices=[('urgent', 'Urgent Task'), ('meeting', 'Unplanned Meeting'), ('support', 'Support/Help'), ('research', 'Research'), ('admin', 'Administrative'), ('other', 'Other')], default='other', help_text='Category of additional activity', max_length=15)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('interrupted', 'Interrupted')], default='completed', max_length=15)),
                ('duration', models.DurationField(blank=True, help_text='Time spent on this activity', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of when it was done')),
                ('impact_on_planned_work', models.TextField(blank=True, help_text='How this activity affected your planned work (if applicable)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending Check-out'), ('completed', 'Completed'), ('absent', 'Absent')], default='pending', max_length=15)),
                ('attendance_status', models.CharField(choices=[('on_time', 'On Time'), ('late', 'Late'), ('absent', 'Absent')], default='on_time', max_length=15)),
                ('checkin_time', models.DateTimeField(blank=True, null=True)),
                ('morning_problems', models.TextField(blank=True, help_text='Any problems or blockers?')),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('afternoon_problems', models.TextField(blank=True, help_text='Any problems encountered during the day?')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or reflection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'user__email'],
            },
        ),
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief description of the goal', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the goal')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('partially_completed', 'Partially Completed'), ('not_achieved', 'Not Achieved'), ('deferred', 'Deferred')], default='pending', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2, help_text='Priority level')),
                ('target_value', models.CharField(blank=True, help_text='Target value or metric (if measurable)', max_length=100)),
                ('achieved_value', models.CharField(blank=True, help_text='Actual achieved value', max_length=100)),
                ('completion_percentage', models.PositiveIntegerField(default=0, help_text='Completion percentage (0-100)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of importance')),
                ('reasons', models.TextField(blank=True, help_text='Reason for not achieving or issues encountered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlannedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief description of the planned activity', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description if needed')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('deferred', 'Deferred'), ('not_completed', 'Not Completed')], default='pending', max_length=15)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2, help_text='Priority level')),
                ('estimated_duration', models.DurationField(blank=True, help_text='Estimated time to complete', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of execution')),
                ('reasons', models.TextField(blank=True, help_text='Reason for not completing or issues encountered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'priority', 'created_at'],
            },
        ),
    ]
