# Generated by Django 5.2.4 on 2025-07-03 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='additionalactivity',
            name='daily_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_activities', to='activities.dailyactivity'),
        ),
        migrations.AddField(
            model_name='activitygoal',
            name='daily_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='activities.dailyactivity'),
        ),
        migrations.AddField(
            model_name='dailygoal',
            name='daily_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goals', to='activities.dailyactivity'),
        ),
        migrations.AddField(
            model_name='plannedactivity',
            name='daily_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_activities', to='activities.dailyactivity'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyactivity',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='additionalactivity',
            unique_together={('daily_activity', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='dailygoal',
            unique_together={('daily_activity', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='plannedactivity',
            unique_together={('daily_activity', 'order')},
        ),
    ]
