# Generated by Django 5.2.4 on 2025-07-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivity',
            name='attendance_status',
            field=models.CharField(choices=[('on_time', 'On Time'), ('late', 'Late'), ('early_checkout', 'Early Checkout'), ('absent', 'Absent')], default='on_time', max_length=15),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Check-out'), ('completed', 'Completed'), ('early_checkout', 'Early Checkout'), ('absent', 'Absent')], default='pending', max_length=15),
        ),
    ]
