# Generated by Django 5.2.4 on 2025-08-22 15:54

import activities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_dailyactivity_attendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='checkin_location',
            field=models.CharField(blank=True, help_text='Format: lat,long', max_length=100, null=True, validators=[activities.models.validate_lat_long]),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='checkout_location',
            field=models.CharField(blank=True, help_text='Format: lat,long', max_length=100, null=True, validators=[activities.models.validate_lat_long]),
        ),
    ]
