# Generated by Django 5.2.4 on 2025-08-25 08:08

import activities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_dailyactivity_checkin_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivity',
            name='checkin_location',
            field=models.CharField(help_text='Format: lat,long', max_length=100, validators=[activities.models.validate_lat_long]),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='checkout_location',
            field=models.CharField(help_text='Format: lat,long', max_length=100, validators=[activities.models.validate_lat_long]),
        ),
    ]
